[package]
  name = "raytracer"
  version = "0.1.0"
  edition = "2024"

[dependencies]

[dev-dependencies]
  cucumber = "0.21"
  tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

[[test]]
  name = "cucumber" # this should be the same as the filename of your test target
  harness = false  # Allows Cucumber to print output instead of libtest
